#!/usr/bin/env python3
import dice
import discord
from discord.ext import commands
import discord
import logging
import random
from env import TOKEN,CHANNEL_ROLL,CHANNEL_TAROT,TAROT_USERS,BASEURL,EXT
import gspread
from oauth2client.service_account import ServiceAccountCredentials

# setup discord.py
client = discord.Client()
e = discord.Embed()
# setup logging
logger = logging.getLogger('oracle')
logger.setLevel(logging.DEBUG)
handler = logging.FileHandler(filename='oracle.log', encoding='utf-8', mode='w')
handler.setFormatter(logging.Formatter('%(asctime)s:%(levelname)s:%(name)s: %(message)s'))
logger.addHandler(handler)
# setup gspread
scope = ['https://www.googleapis.com/auth/spreadsheets', 'https://www.googleapis.com/auth/drive']
creds = ServiceAccountCredentials.from_json_keyfile_name('secret.json', scope)
gclient = gspread.authorize(creds)

def roll_dice(notation):
    roll = dice.roll(notation)
    result = int(roll)
    return roll,result

def random_tarot(exclude):
    if exclude == '':
        random_card = str(random.choice(range(00, 77, 1)))
        return (BASEURL + random_card.zfill(2) + EXT)
    elif exclude is not None:
        excludelist = exclude.split(',')
        include = []
        exclude = []
        for i in excludelist:
            if int(i) >= 0:
                include.append(i)
            elif int(i) < 0:
                exclude.append(i)
        if include:
            specific_card = include[0]
            return (BASEURL + specific_card.zfill(2) + EXT)
        elif exclude:
            random_card = str(random.choice([i for i in (range(00, 77, 1)) if not i in exclude]))
            return (BASEURL + random_card.zfill(2) + EXT)

def get_question(language):
    file = gclient.open_by_key("1mI_WJAUjUwVQPHn3VqWtgofKn1CNStyPY88dUnZMbYo")
    rowcount = file.worksheet(language).row_count
    random_question = random.randint(1, rowcount)
    vraag = file.worksheet(language).row_values(random_question)[0]
    return vraag
 
def help_text():
    file = open('usage.md', 'r')
    contents = file.read()
    return (contents)

@client.event
async def on_message(message):
    # we do not want the bot to reply to itself
    if message.author == client.user:
        return
    if message.content.startswith('!help'):
        msg = format(help_text())
        await message.author.send (msg)
    if message.content.startswith('!roll'):
        channel = client.get_channel(int(CHANNEL_ROLL))
        parameters = message.content.split(' ', 1)
        if len(parameters) == 2:
            param = parameters[1]
            roll,result = roll_dice(param)
            msg = 'Rolling %s for {0.author.mention}: `%s`'.format(message) % (param,roll)
            await channel.send (msg)
    if message.content.startswith('!tarot'):
        channel = client.get_channel(int(CHANNEL_TAROT))
        parameters = message.content.split(' ', 1)
        del parameters[0]
        allowed_users = TAROT_USERS
        if str(message.author.id) in allowed_users:
            if not parameters:
                exclude = ''
            elif parameters:
                exclude = parameters[0]
            image_url = random_tarot(exclude)
            embed = e.set_image(url=image_url)
            await channel.send (embed=embed)
        else:
            msg = format('You do not have the Sight')
            await message.author.send (msg)
         
@client.event
async def on_ready():
    print('### Active with id %s as %s  ###' % (client.user.id,client.user.name) )
    activity = discord.Activity(name='the threads of fate (pm !help for help)', type=discord.ActivityType.watching)
    await client.change_presence(activity=activity)
    
if __name__ == '__main__':
    client.run(TOKEN)
